### ISSUE TITLE
克隆下来的项目没有project.config.json

### ISSUE THREAD

**Issue by xiaomizhou66** [dyq086/wepy-mall#44]
刚入门，请问克隆下来的项目，没有project.config.json文件，是因为是1.70之前的版本么？是否是直接在项目中自行添加这个文件即可？

**Comment by mafeifan** [comment]
自己新建个就行了
https://tencent.github.io/wepy/document.html#/?id=wepy%E9%A1%B9%E7%9B%AE%E7%9A%84%E5%88%9B%E5%BB%BA%E4%B8%8E%E4%BD%BF%E7%94%A8
