### ISSUE TITLE
本地代码预览授权登录和线上版本不一致问题

### ISSUE THREAD

**Issue by ccj-mlp** [dyq086/wepy-mall#46]
本地代码预览时弹出的是单独的授权页面，而线上的版本是直接弹出授权的模态框，这个是代码有所变动吗？请大神解答

**Comment by dyq086** [comment]
由于微信官方修改了 getUserInfo、authorize 接口，无法弹出授权窗口，所以现在无法实现一进入微信小程序就弹出授权窗口，只能通过 button 去触发
