### ISSUE TITLE
npm install 时报错

### ISSUE THREAD

**Issue by ITzhewei** [dyq086/wepy-mall#53]
npm WARN wepy-compiler-less@1.3.14 requires a peer of less@^3.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN wxYuHanStore@1.0.2 No repository field.

audited 7066 packages in 4.426s
found 3 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by dyq086** [comment]
试一下用cnpm
