### ISSUE TITLE
这个项目是不是已经不维护了？

### ISSUE THREAD

**Issue by donitry** [dyq086/wepy-mall#62]
演示程序倒是可以看到，但是代码clone到本地就不行了，服务器接口都不通了，是不是搬迁了？
`http://api-mall.dyq086.cn/emall/goods/list?cateidOne=1&cateidTwo=0&price=0&sales=2`
这样的连接请求已经404了。

**Comment by dyq086** [comment]
http://api-mall.dyq086.cn/emall/api/goods/list?cateidOne=1&cateidTwo=0&price=0&sales=2
