### ISSUE TITLE
请问服务器还在工作吗，调式的接口报502错误

### ISSUE THREAD

**Issue by zhaohangPG** [dyq086/wepy-mall#65]
编译完毕后在开发者工具打开，没有获取到数据，控制台报502错误
请问是接口的问题吗
![502报错](https://user-images.githubusercontent.com/47552314/84624270-a246a680-af13-11ea-8f41-625960992424.png)

**Comment by zhaohangPG** [comment]
我看已经关闭的issue有提到这个问题，是不是服务器挂了

**Comment by dyq086** [comment]
服务挂了找我重启

**Comment by liaorenqian** [comment]
怎么找你重启
